### ISSUE TITLE
Error loading TS-DOS on NEC PC-8201A

### ISSUE THREAD

**Issue by benhoh** [Jeff-Birt/Backpack#1]
Hey Jeff, I just bought a Backpack+ with a preloaded SD card for my NEC PC-8201A, and am attempting to load TS-DOS into RAM, via `run “com:9n81xn”`. The `INITIAL PROGRAM LOADER II` opens, but crashes on line 40.

When I list the program in memory, line 40 reads:

`40 OPEN"COM:98N1DNN" FOR OUTPUT AS #1`

Given that you're specifying different ways to set up the serial port for different devices (`com:9n81xn` for the NEC), is it loading the right program loader?

**Comment by benhoh** [comment]
I did a bit of digging and have realised that I should probably be loading `INITIAL PROGRAM LOADER III` for the NEC, rather than `INITIAL PROGRAM LOADER II`. 

How can I load LOADER III? Should I be changing the IPL file in the CLI's `boot` settings to `bootn` instead of `boot`? E.g.

`# boot 0 bootn`

**Comment by benhoh** [comment]
I changed the IPL settings as above and was met with success! Given that it accounts for both Tandy and NEC machines, Is there any reason BOOTN isn't the default? And if there is a good reason, I think the documentation would do with a clearer note about the need to reconfigure.

**Comment by 48kRAM** [comment]
Hmm...I don't actually know what 'bootn' is. The 'boot' bootstrap file

https://github.com/Jeff-Birt/Backpack/blob/main/BPD%20Files/bootstrap/BOOT

should autodetect an NEC system and load the correct "sector" from the SD card.

**Comment by benhoh** [comment]
@48kRAM That's not what's in my boot file. On the preloaded BPD+ SD (https://github.com/Jeff-Birt/Backpack/blob/main/BPD%2B%20Files/SD_Card/Epson%20BPD%2B%20SD%20Card.zip), the BOOT file is different:

```
10 CLS:?"---INITIAL PROGRAM LOADER II---
20 ?"      WAIT A MINUTE!":CLOSE
30 IF PEEK(1)=171 THEN M=4 ELSE M=3
40 OPEN"COM:98N1DNN" FOR OUTPUT AS #1
50 ?#1,"FF";CHR$(M);
60 FOR I=1 TO 10:NEXT:CLOSE
70 RUN"COM:98N1ENN
```

… whereas BOOTN is this:

```
10 CLS:PRINT"---INITIAL PROGRAM LOADER III---"
20 PRINT"      WAIT A MINUTE!":CLOSE
25 A$="COM:98N1ENN"
30 IF PEEK(1)=171 THEN M=4 ELSE M=3
35 IF PEEK(1)=148 THEN M=5:A$="COM:9N81XN"
40 OPENA$ FOR OUTPUT AS #1
50 PRINT#1,"FF";CHR$(M);
60 FOR I=1 TO 10:NEXT:CLOSE
70 RUNA$
```

This is described on p55 of the manual. It'd seem that BOOTN is functionally similar to the file you're pointing to, but the contents of the BPD+ BOOT — the first program above — doesn't seem to use the right serial port setup for the NEC at all, and doesn't go the right sector for the NEC (which I assume the value 5 is meant to denote).

**Comment by Jeff-Birt** [comment]
As 48kRAM mentioned the bootstrap file is supposed to detect the type of computer and load the proper boot file. It looks like the IPL got reverted to an older version by mistake. Thanks for pointing this out. I will look into it.

**Comment by benhoh** [comment]
Thanks @Jeff-Birt! In any case, it's working after manually resetting it.
