### ISSUE TITLE
Attempting to load the IPL on T102 returns ?DS Error

### ISSUE THREAD

**Issue by markaudacity** [Jeff-Birt/Backpack#2]
Following the instructions in the PDF, the result of `run"com:98n1e` and then switching on the BPDD is `?DS Error`, which is a "direct statement in file" error.
I have uploaded the most recent firmware and verified via the CLI that the SD card is visible.

**Comment by markaudacity** [comment]
Tried it on my M100. 
It loads and displays the IPL wait screen, then hangs forever. Power cycling the BPDD results in TS-DOS beginning to load, but once it loads, it throws a `?FC` illegal function call error on line 8.

**Comment by Jeff-Birt** [comment]
The BOOT file got goofed up somehow. I thought I had fixed this problem weeks ago but apparently not. I just uploaded a new ZIP file for the BPD+. The only thing that is changed is the BOOT file in SECTOR0. You might also double check that your BPD+ is still set to MT mode.

**Comment by markaudacity** [comment]
> The BOOT file got goofed up somehow. 
Thanks for the quick response. Debugging the code is still a bit advanced for me!

**Comment by markaudacity** [comment]
No dice. The updated BPD+ SD Card.zip gives the same results. Won’t load without power-cycling the BPD after the IPL loads, after it finishes with “Installing TS-DOS” it throws a ?FC error on line 8, and the TS-DOS launcher in Ultimate Rom II reports a disk error when I try to load it.

**Comment by Jeff-Birt** [comment]
Ah, the URII explains it. The URII contains a version of TS-DOS so you can't bootstrap a second version into RAM. The version of TS-DOS on the URII is special, it requires a special file to be on every disk. When you use TS-DOS from URII it first loads this file (the UI) and then you can use TS-DOS. When you close TS-DOS it removes the file from RAM. 

NOTE: If you want to use multiple directories you will need a copy of the file in each one. 

I have that file 'somewhere'. Give me a bit to search for it and then I'll add it to the repo.

**Comment by Jeff-Birt** [comment]
> No dice. The updated BPD+ SD Card.zip gives the same results. Won’t load without power-cycling the BPD after the IPL loads, after it finishes with “Installing TS-DOS” it throws a ?FC error on line 8, and the TS-DOS launcher in Ultimate Rom II reports a disk error when I try to load it.

OK, got it sorted out. To use the Ultimate ROM II you need to put DOS100.CO (for M100, T102 or DOS200.CO for Model 200) in the ROOT, or which ever folder you are in when you want to start up TS-DOS. It loads it on the fly. There is more information in the URII manual about clearing high memory when switching between TS-DOS and other programs that use that area of memory.

**Comment by markaudacity** [comment]
That unfortunately didn't fix it. URII still reports Disk Error with DOS100.CO in the root directory, trying to `run"com:98n1e"` still returns a `?DS Error`.

**Comment by Jeff-Birt** [comment]
Quit trying to bootstrap TSDOS from the Backpack. DO NOT TRY TO RUN "COM:98N1E"!! This method is ONLY used if you do not have some form of TS-DOS on ROM. You already have a form of TS-DOS in your URII.

Do a hard reset of your computer. Start the URII with CALL 63013,1. Then select TS-DOS from the URII menu. The URII ROM will then load DOS100.CO from the Backpack.

**Comment by markaudacity** [comment]
Cold booting and re-initializing URII worked one time, was able to copy a file, reported a disk error after copying the file, and had not worked since even after cold booting and re-initializing again.

**Comment by Jeff-Birt** [comment]
The version of TS-DOS on the URII is TS-DOS version in that every time to click the TS-DOS button in the URII menu it will load the DOSxxx.CO file from the disk. For the original TPDD1 and TPDD2 drives this meant you needed to include the DOSxxx.CO file on every disk you would want to launch TS-DOS from.

The drives themselves did not support directories but Traveling Software came out with DeskLink to allow connecting the M100 to a PC via serial cable and transferring files. DeskLink did support directories as does the Backpack. This means that when you launch TS-DOS from the URII it will look in the directory the Backpack was last changed to. If you don't change back to the ROOT directory while in your TS-DOS session it won't start up again until you go into the CLI and CD .. back to ROOT. Alternatively, you could add DOSxxx.co to each directory on the card you will be using with TSDOS.

Also keep in mind that the Backpack will time out and go to sleep after 30 seconds or so. You can reconfigure this in the CLI. I noticed when using the URII yesterday that my Backpack would time out and I would need to try again. (The first try work the Backpack up.) Other versions of TS-DOS send commands multiple times so this is not an issue, but again the URII version is a bit special.

I was using a URII rom image from a DAR yesterday. My original URII ROM got quite flakey. I took apart the 'wrapper' and cleaned the contacts which helped for a while but eventually it was too flakey to rely on.

**Comment by markaudacity** [comment]
I haven’t changed directories from the root. 
I went back to the CLI and did a cd just to make sure, cold booted, pulled the URII option ROM and buffed the contacts, reinstalled it, reinitialized URII, and it still won’t work. 
DOS100.CO is in the root directory. 
I haven’t touched anything in SECTOR0.

**Comment by Jeff-Birt** [comment]
Are you trying this on an M100? The early units had wrong resistors in the RS232 output lines, they fitted 5.6K rather than 330ohms. This causes too low a voltage on the outputs which is especially a problem when the handshaking signals are looped back. I did a video about this recently. In the video description is a link to a PDF of the TSB which gives the serial number cut off. 

https://youtu.be/KPFnwv_nDD8

The other thing you can try if you have at least one RAM expansion module installed is to remove the URII. Do a hard reset. Go into the BDP CLI and do FACTORY which will reset to factory defaults. Then follow the procedure in the manual to bootstrap TSDOS into RAM. This will take the URII out of the picture.

**Comment by Jeff-Birt** [comment]
The other thing that will cause this is a weak battery. You must have a good 1.5V alkaline battery, NOT a 1.2V rechargeable battery.
