### ISSUE TITLE
Unable to update -- DISK: unknown command

### ISSUE THREAD

**Issue by vldmrrr** [Jeff-Birt/Backpack#5]
I am trying to change firmware from Tandy to Epson. When I enter DISK command I get get UNKNOWN COMMAND in response - does not matter if I add U argument or not.

**Comment by Jeff-Birt** [comment]
Hi, the BPD+ comes with the M100 firmware installed. The firmware update command is a bit different between the two. Page 19 of the Backpack+ manual shows the syntax 'BOOT U filename' . Where filename is the name of the Epson firmware file. After rebooting your BPD+ will now be in Epson mode and the Epson 'DISK U filename' syntax will work.

**Comment by vldmrrr** [comment]
My bad, thank you.
